# spin a container to install cores and libraries
# exec into it with 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: arduino-builder-api-jobs
  name: installer-example
spec:
  selector:
      matchLabels:
        app: installer-example
  template:
    metadata:
      labels:
        app: installer-example
    spec:
      containers:
      - name: installer
        image: arduino/cli
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        env:
          - name: ARDUINO_DIRECTORIES_DATA
            value: /var/run/arduino/directories-data
          - name: ARDUINO_DIRECTORIES_USER
            value: /var/run/arduino/directories-user
        volumeMounts:
        # Where to install packages and libraries
        - name: directories-data
          mountPath: /var/run/arduino/directories-data
          readOnly: false
        - name: directories-user
          mountPath: /var/run/arduino/directories-user
          readOnly: false
        - name: compilation-output
          mountPath: /var/run/arduino/compilations-output
          readOnly: false
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
        imagePullPolicy: IfNotPresent
      volumes:
        - name: directories-data
          persistentVolumeClaim:
              claimName: data-directory-volume-claim
        - name: directories-user
          persistentVolumeClaim:
              claimName: user-directory-volume-claim
        - name: compilation-output
          persistentVolumeClaim:
              claimName: compilation-output-volume-claim
