apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: arduino-builder-api-jobs
  name: library-volume-claim
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
