// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CompilationLog struct {
	Type          string `json:"type"`
	CompilationID string `json:"compilationId"`
	Text          string `json:"text"`
}

type CompilationStatus struct {
	ID *string `json:"id"`
}

type CompilationUpdate struct {
	Type          string `json:"type"`
	CompilationID string `json:"compilationId"`
	State         string `json:"state"`
}
